language: python

python:
  - "3.5"

env:
  CODECLIMATE_REPO_TOKEN: 57667760e1e63a9934ef7fc199a20e9e8038e36aef1b4b2e50bed358eb8c151a

install: "pip install -r requirements.txt"

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec
  - coverage run --source=personal_website -m manage test; coverage report

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
